### PR TITLE
prepare for 0.4 release

### PR DESCRIPTION
**Pull request by yomimono**

### CODE REVIEW

**Comment by haesbaert** [comment]
Heya, hold this a bit please.

i want to make minor changes on dhcp_wire api, will submit today.

**Comment by haesbaert** [comment]
Actually disregard my comment, it was commited already (wanted to make pkt_of_buf return Result).
Are we dropping 4.02.3 in mirage after all ?

**Comment by hannesm** [comment]
hmm, this commit https://github.com/yomimono/charrua-client/commit/43ea969df30102485c0e847f50cd8c115337f9e2 shows that somewhere in `Dhcp_wire.pkt_of_buf` there's still an exception raised (but I've no clue which wire data lead to an exception)... would be great to have an exception-less `pkt_of_buf`...

**Comment by haesbaert** [comment]
I've pushed 5a25d8f9362872d0f49ad3d66300c24fd8a45451
At any rate I don't see why this shouldn't go in, I'm merging.

**Pull request merged**
