### PR TITLE
Re-implement UDP checksum on input.

### PR DESCRIPTION
**Pull request by haesbaert**
The unmarshal function doesn't verify checksum, so we have to do it ourselves.
There doesn't seem to be a simple API for verifying IPV4 header checksum in Tcpip.

Can anyone clarify why this is not done by the unmarshal function ? 
This seems incredibly error prone, and we should not give an option for the user to keep a packet if the checksum is incorrect imho.

### CODE REVIEW

**Comment by yomimono** [comment]
True about the IPV4 header checksum; there should be a convenience function for this like there is for TCP and UDP checksums.

In `tcpip` the original authors decided that it would be better to check the checksum 0 times than to check it more than once, given that it was not possible to know whether it had been checked already.  I agree that checking it 0 times is not a good solution.

**Comment by haesbaert** [comment]
Ack, I'll see if I can come up with something for Tcpip.
Meanwhile, I think this PR is pretty safe, can I get an ok ?

**Comment by haesbaert** [comment]
Ah thanks, I'll have a look since I'm using this guard idiom extensively in ssh, would be nice if Rresult has something

**Comment by haesbaert** [comment]
So I haven't found but found a better assert_error(), meanwhile I converted the length check to use guard, at least it's not so alone anymoar.

**Pull request merged**
