### PR TITLE
Merge charrua-client and charrua-unix into charrua-core

### PR DESCRIPTION
**Pull request by avsm**
Also adding charrua-server shortly, and then this repo can be renamed charrua-dhcp

### CODE REVIEW

**Comment by avsm** [comment]
Pushed extra changes to also merge https://github.com/haesbaert/charrua-unix into this repository as well.

**Comment by avsm** [comment]
Linking to comments in https://github.com/mirage/charrua-core/commit/712696f976bd8d4a398836d697bcae169858366d so they dont get lost...

**Comment by samoht** [comment]
Merging the 3 repositories looks like a good idea to me. The number of changes is quite big, so not sure I will be able to review everything ... I guess as long as it builds and that no history is lost, I guess we can fix smaller issues in subsequent PRs.

**Comment by haesbaert** [comment]
I agree, it's easier to review and ajust later, as long as nothing blows up
for now we should be fine.

Many thanks for this !

**Comment by samoht** [comment]
Also, you need https://github.com/samoht/charrua-client.git#with-cdhcpc to compile charrua-client with the latest charrua-core.

**Comment by avsm** [comment]
@samoht can i request a rebase :)

**Comment by haesbaert** [comment]
I noticed server/ only has the metafiles for unix/. Is that correct ?

**Comment by avsm** [comment]
@haesbaert fixed up in https://github.com/mirage/charrua-core/pull/59 -- the only files needed are in `unix/` for the server. boilerplate removal ftw :-)

**Comment by haesbaert** [comment]
Great ! Just go ahead an merge them please, i cant login to github

**Pull request merged**
